///|
#external
pub type Image

///|
#external
pub type Texture

///|
#external
pub type RenderTexture

///|
#external
pub type Font

///|
#external
pub type Sound

///|
#external
pub type Music

///|
#external
pub type Model

///|
#external
pub type Shader

///|
#external
pub type Wave

///|
#external
pub type AudioStream

///|
#external
pub type Mesh

///|
#external
pub type Material

///|
#external
pub type ModelAnimations

///|
#external
pub type FilePathList

///|
#external
pub type GlyphInfoArray

///|
#external
pub type AutomationEventList

///|
#external
pub type VrStereoConfig

///|
#external
pub type MaterialsArray

///|
#external
pub type AudioBuffer
