///|
pub let screen_w : Int = 1840

///|
pub let screen_h : Int = 1010

///|
pub let target_fps : Int = 120

///|
pub let board_x0 : Int = 26

///|
pub let board_y0 : Int = 84

///|
pub let cell : Int = 56

///|
pub let grid_w : Int = 25

///|
pub let grid_h : Int = 13

///|
pub let board_w : Int = grid_w * cell

///|
pub let board_h : Int = grid_h * cell

///|
pub let panel_x0 : Int = board_x0 + board_w + 24

///|
pub let panel_w : Int = screen_w - panel_x0 - 24

///|
pub let train_lane_n : Int = 3

///|
pub let junction_n : Int = 4

///|
pub let max_trains : Int = 24

///|
pub let max_inspectors : Int = 3

///|
pub let max_particles : Int = 420

///|
pub let max_lives : Int = 3

///|
pub let goal_routed : Int = 20

///|
pub let round_time_limit : Float = 210.0

///|
pub let train_exit_x : Float = 23.4

///|
pub let train_spawn_x : Float = 1.0

///|
pub let player_move_t : Float = 0.105

///|
pub let inspector_move_t : Float = 0.145

///|
pub let emp_cost : Float = 35.0

///|
pub let score_route_ok : Int = 120

///|
pub let score_route_bad : Int = -70

///|
pub let score_toggle : Int = 20

///|
pub let score_emp_hit : Int = 50

///|
pub let score_win_bonus : Int = 1000

///|
pub let start_x : Int = 2

///|
pub let start_y : Int = 10
