///|
pub let screen_w : Int = 1680

///|
pub let screen_h : Int = 960

///|
pub let target_fps : Int = 120

///|
pub let board_cols : Int = 24

///|
pub let board_rows : Int = 18

///|
pub let board_cells : Int = board_cols * board_rows

///|
pub let tile_void : Int = 0

///|
pub let tile_floor : Int = 1

///|
pub let tile_wall : Int = 2

///|
pub let tile_goal : Int = 3

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_level_clear : Int = 2

///|
pub let state_campaign_clear : Int = 3

///|
pub let touch_none : Int = 0

///|
pub let touch_left : Int = 1

///|
pub let touch_right : Int = 2

///|
pub let touch_up : Int = 3

///|
pub let touch_down : Int = 4
