///|
pub let screen_w : Int = 1280

///|
pub let screen_h : Int = 720

///|
pub let target_fps : Int = 120

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_stage_clear : Int = 2

///|
pub let state_game_over : Int = 3

///|
pub let ring_count : Int = 4

///|
pub let max_enemies : Int = 160

///|
pub let max_bullets : Int = 240

///|
pub let max_enemy_bullets : Int = 260

///|
pub let max_flares : Int = 24

///|
pub let max_particles : Int = 520

///|
pub let max_shocks : Int = 180

///|
pub let base_radius : Float = Float::from_int(120)

///|
pub let ring_gap : Float = Float::from_int(62)

///|
pub let player_hit_r : Float = Float::from_int(20)

///|
pub let player_turn_speed : Float = 2.9

///|
pub let player_switch_cd : Float = 0.17

///|
pub let player_shot_cd : Float = 0.15

///|
pub let player_beam_cd : Float = 1.2

///|
pub let player_phase_max : Float = Float::from_int(100)

///|
pub let phase_drain : Float = Float::from_int(24)

///|
pub let phase_recover : Float = Float::from_int(16)

///|
pub let player_invuln_t : Float = 0.66

///|
pub let enemy_base_speed : Float = 1.1

///|
pub let enemy_speed_stage : Float = 0.08

///|
pub let enemy_fire_base : Float = 1.2

///|
pub let stage_time : Float = Float::from_int(36)

///|
pub let stage_clear_delay : Float = 1.8

///|
pub let pi : Float = 3.14159265

///|
pub let tau : Float = 6.28318530
