///|
pub let screen_w : Int = 1820

///|
pub let screen_h : Int = 1000

///|
pub let target_fps : Int = 120

///|
pub let board_x0 : Int = 28

///|
pub let board_y0 : Int = 86

///|
pub let cell : Int = 58

///|
pub let grid_w : Int = 27

///|
pub let grid_h : Int = 13

///|
pub let board_w : Int = grid_w * cell

///|
pub let board_h : Int = grid_h * cell

///|
pub let panel_x0 : Int = board_x0 + board_w + 20

///|
pub let panel_w : Int = screen_w - panel_x0 - 20

///|
pub let max_guards : Int = 6

///|
pub let max_loot : Int = 8

///|
pub let max_smokes : Int = 5

///|
pub let max_particles : Int = 420

///|
pub let loot_need : Int = 6

///|
pub let start_x : Int = 2

///|
pub let start_y : Int = 6

///|
pub let exit_x : Int = grid_w - 2

///|
pub let exit_y : Int = 6

///|
pub let player_move_t : Float = 0.11

///|
pub let guard_move_t : Float = 0.15

///|
pub let smoke_ttl : Float = 4.8

///|
pub let run_time_limit : Float = 210.0

///|
pub let smoke_cost : Float = 34.0

///|
pub let score_blueprint : Int = 280

///|
pub let score_keycard : Int = 360

///|
pub let score_gold : Int = 180

///|
pub let score_escape : Int = 1200
