///|
pub let screen_w : Int = 1720

///|
pub let screen_h : Int = 980

///|
pub let target_fps : Int = 120

///|
pub let max_board : Int = 12

///|
pub let max_cells : Int = max_board * max_board

///|
pub let cell_unknown : Int = 0

///|
pub let cell_fill : Int = 1

///|
pub let cell_cross : Int = 2

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_level_clear : Int = 2

///|
pub let state_campaign_clear : Int = 3

///|
pub let state_level_fail : Int = 4

///|
pub let tool_fill : Int = 1

///|
pub let tool_cross : Int = 2

///|
pub let dir_none : Int = 0

///|
pub let dir_left : Int = 1

///|
pub let dir_right : Int = 2

///|
pub let dir_up : Int = 3

///|
pub let dir_down : Int = 4
