///|
pub let screen_w : Int = 1366

///|
pub let screen_h : Int = 768

///|
pub let target_fps : Int = 120

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_stage_clear : Int = 2

///|
pub let state_game_over : Int = 3

///|
pub let obj_wall : Int = 0

///|
pub let obj_orb : Int = 1

///|
pub let obj_gate_alpha : Int = 2

///|
pub let obj_gate_beta : Int = 3

///|
pub let obj_boost : Int = 4

///|
pub let obj_jump_bar : Int = 5

///|
pub let lane_count : Int = 5

///|
pub let max_objs : Int = 360

///|
pub let max_particles : Int = 460

///|
pub let max_trails : Int = 180

///|
pub let base_speed : Float = 680.0

///|
pub let speed_stage_gain : Float = 70.0

///|
pub let player_jump_speed : Float = 860.0

///|
pub let player_gravity : Float = 2550.0

///|
pub let stage_base_distance : Float = 5200.0

///|
pub let stage_distance_growth : Float = 1800.0

///|
pub let phase_drain_per_sec : Float = 21.0

///|
pub let phase_recover_per_sec : Float = 18.0

///|
pub let phase_switch_cd : Float = 0.24

///|
pub let invuln_time : Float = 0.65

///|
pub let combo_decay_time : Float = 3.8
