///|
pub let screen_w : Int = 1280

///|
pub let screen_h : Int = 720

///|
pub let target_fps : Int = 120

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_stage_clear : Int = 2

///|
pub let state_game_over : Int = 3

///|
pub let obj_rock : Int = 0

///|
pub let obj_mine : Int = 1

///|
pub let obj_data : Int = 2

///|
pub let obj_oxygen : Int = 3

///|
pub let obj_current : Int = 4

///|
pub let obj_scrap : Int = 5

///|
pub let max_objs : Int = 420

///|
pub let max_particles : Int = 560

///|
pub let max_ripples : Int = 64

///|
pub let max_trails : Int = 180

///|
pub let player_r : Float = Float::from_int(22)

///|
pub let base_scroll : Float = Float::from_int(210)

///|
pub let stage_scroll_gain : Float = Float::from_int(24)

///|
pub let player_accel : Float = Float::from_int(920)

///|
pub let player_drag : Float = Float::from_int(2)

///|
pub let player_max_speed : Float = Float::from_int(360)

///|
pub let oxygen_drain : Float = Float::from_int(3)

///|
pub let oxygen_data_bonus : Float = Float::from_int(2)

///|
pub let oxygen_pickup : Float = Float::from_int(24)

///|
pub let sonar_cd_time : Float = 2.1

///|
pub let sonar_time : Float = 0.76

///|
pub let sonar_reveal_r : Float = Float::from_int(220)

///|
pub let sonar_destroy_r : Float = Float::from_int(70)

///|
pub let dash_cd_time : Float = 1.3

///|
pub let dash_time : Float = 0.19

///|
pub let dash_speed : Float = Float::from_int(560)

///|
pub let invuln_time : Float = 0.62

///|
pub let stage_base_goal : Float = Float::from_int(1900)

///|
pub let stage_goal_gain : Float = Float::from_int(620)

///|
pub let stage_clear_delay : Float = 1.8

///|
pub let spawn_start_y : Float = -120.0

///|
pub let spawn_spacing_min : Float = 70.0

///|
pub let spawn_spacing_max : Float = 170.0

///|
pub let cave_min_half : Float = Float::from_int(150)

///|
pub let cave_max_half : Float = Float::from_int(290)

///|
pub let cave_x_margin : Float = Float::from_int(84)
