///|
pub let screen_w : Int = 1720

///|
pub let screen_h : Int = 980

///|
pub let target_fps : Int = 120

///|
pub let board_n : Int = 15

///|
pub let max_cells : Int = board_n * board_n

///|
pub let state_title : Int = 0

///|
pub let state_play : Int = 1

///|
pub let state_result : Int = 2

///|
pub let player_empty : Int = 0

///|
pub let player_human : Int = 1

///|
pub let player_ai : Int = 2

///|
pub let dir_none : Int = 0

///|
pub let dir_left : Int = 1

///|
pub let dir_right : Int = 2

///|
pub let dir_up : Int = 3

///|
pub let dir_down : Int = 4
