name: publish-community
run-name: publish to moonbit-community/raylib
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: moon version
        run: |
          moon version --all
      - name: moon update
        run: |
          moon update
      - name: rename module
        run: |
          sed -i 's|tonyfettes/raylib|moonbit-community/raylib|g' moon.mod.json
          find . -name 'moon.pkg' -not -path './.mooncakes/*' -not -path './examples/*' -exec sed -i 's|tonyfettes/raylib|moonbit-community/raylib|g' {} +
      - name: moon check
        run: |
          moon check --target native
      - name: publish moonbit-community/raylib
        run: |
          echo $SECRET > ~/.moon/credentials.json
          moon publish
          rm ~/.moon/credentials.json
        env:
          SECRET: ${{ secrets.MOONCAKES_MOONBIT_COMMUNITY_TOKEN }}
